BDKrishok/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Models
{
    [Table("Category")]
    public class Category
    {
        public int Id { get; set; }

        [Required]
        [StringLength(200)]

        public string Name { get; set; }

        public int? CategoryId { get; set; }

        public virtual ICollection<Category> Categories { get; set; }

        public virtual Category SubCategory { get; set; }

    }
}

BDKrishok/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Models;

namespace BDKrishok.Controllers
{
    public class CategoryController : Controller
    {
        private _BDKrishokDB db = new _BDKrishokDB();

        // GET: Category
        public ActionResult Index()
        {
            var category = db.Category.Include(c => c.SubCategory);
            return View(category.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            ViewBag.TopCategoryList = db.Category.OrderByDescending(c => c.Id).Take(10).ToList();
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CategoryId")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Category.Add(category);
                db.SaveChanges();
                ViewBag.TopCategoryList = db.Category.OrderByDescending(c => c.Id).Take(10).ToList();
                return RedirectToAction("Create");
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", category.CategoryId);
            
            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", category.CategoryId);
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CategoryId")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", category.CategoryId);
            return View(category);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Category.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            else
            {
                db.Category.Remove(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BDKrishok/Controllers/MainCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;

namespace BDKrishok.Controllers
{
    public class MainCategoryController : Controller
    {
        private _BDKrishokDB db = new _BDKrishokDB();
        // GET: MainCategory
        public ActionResult Category(int? category)
        {
            if (category != null)
            {
                int cId = Convert.ToInt32(Request.QueryString["category"]);
                ViewBag.CategoryList = db.Category.Where(c => c.CategoryId == cId).ToList();
                ViewBag.Cat = db.Category.FirstOrDefault(c => c.Id == category);
                return View();
            }
            else
            {
                return RedirectToAction("Home", "Home");
            }

            
        }

        public ActionResult SubCategory(int? subcategory)
        {
            if (subcategory != null)
            {
                int cId = Convert.ToInt32(Request.QueryString["subcategory"]);
                ViewBag.CategoryList = db.Category.Where(c => c.CategoryId == cId).ToList();
                return View();
            }
            else
            {
                return RedirectToAction("Home", "Home");
            }


        }
    }
}

BDKrishok/Views/MainCategory/Category.cshtml
@using Models;
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";
    List<Category> CategoryList = ViewBag.CategoryList;
    Category cat = ViewBag.Cat;
}
<hr/>
<a href="../MainCategory/Category?category=@cat.Id"><h4>@cat.Name</h4></a>

<hr/>
<ul class="nav nav-tabs">
    


        @{
        foreach (var category in CategoryList)
        {
            <li class="nav-item">
            <a href='@Url.Action("Category", "MainCategory", new {category = category.Id})' class="nav-link active btn" style="margin-left: 5px; margin-right: 5px; padding: 0 0">

            <h2 class="card-title" style="font-size: 24px; text-align: center">@category.Name</h2></a>
            </li>
        }
    }
</ul>
@*<div class="row container">
    @{
        foreach (var category in CategoryList)
        {
            
            <a href='@Url.Action("Category", "MainCategory", new {category = category.Id})' class="btn" style="margin-left: 5px; margin-right: 5px; padding: 0 0">
                <div class="card h-100" style="background: darkslategray; color: white;border: 3px solid darksalmon">
                    <div class="card-body">
                        <h2 class="card-title" style="font-size: 24px; text-align: center">@category.Name</h2>
                    </div>
                </div>
            </a>
        }
    }
</div>
<hr/>*@
<section style="height: 500px">

</section>

BDKrishok/Views/MainCategory/SubCategory.cshtml
@using Models

@{
    ViewBag.Title = "SubCategory";
    Layout = "~/Views/Shared/_ClientLayout.cshtml";

    List<Category> CategoryList = ViewBag.CategoryList;
}
<div class="row">
    @{
        foreach (var category in CategoryList)
        {
            <div class="col-md-2 mb-2" style="margin-left: 15px; margin-right: 15px;padding: 0 0">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title" style="font-size: 24px;text-align: center">@category.Name</h2>
                    </div>
                    <div class="card-footer" style="padding: 10px">
                        <p class="card-text" style="font-size: 12px">এখানে কিছু বর্ণনা থাকবে এখানে কিছু বর্ণনা থাকবে< এখানে কিছু বর্ণনা থাকবে<</p>
                        <center>
                            @if (category.Categories.Any())
                            {
                                <a href='@Url.Action("SubCategory", "MainCategory", new {subcategory = category.Id})'>আরো জানুন</a>
                            }
                        </center>
                    </div>
                </div>

            </div>
        }
    }
</div>